# Schema Definitions

### Create Organization
POST http://localhost:9019/organizations
Content-Type: application/json

{
  "organizationId": "",
  "name": "Org1",
  "description": "My organization."
}

> {% client.global.set('orgId', response.body.organizationId) %}


### Create Unit
POST  http://localhost:9019/organizations/{{orgId}}/units
Content-Type: application/json

{
  "organizationId": "{{orgId}}",
  "unitId": "",
  "name": "Unit1",
  "description": "My unit."
}

> {% client.global.set('unitId', response.body.unitId) %}

### Create Context
POST http://localhost:9019/organizations/{{orgId}}/units/{{unitId}}/contexts
Content-Type: application/json

{
  "organizationId": "{{orgId}}",
  "unitId": "{{unitId}}",
  "contextId": "",
  "namespace": "io.vlingo.schemata",
  "description": "Schemata Context."
}

> {% client.global.set('contextId', response.body.contextId) %}

### Create Schema
POST http://localhost:9019/organizations/{{orgId}}/units/{{unitId}}/contexts/{{contextId}}/schemas
Content-Type: application/json

{
  "organizationId": "{{orgId}}",
  "unitId": "{{unitId}}",
  "contextId": "{{contextId}}",
  "schemaId": "",
  "category": "Event",
  "name": "SchemaDefined2",
  "scope": "Private",
  "description": "Schemata was defined event."
}

> {% client.global.set('schemaId', response.body.schemaId) %}

<> 2019-09-13T105524.201.txt
<> 2019-09-13T105508.201.txt
<> 2019-09-13T105413.201.txt

### Create Schema Version
POST http://localhost:9019/organizations/{{orgId}}/units/{{unitId}}/contexts/{{contextId}}/schemas/{{schemaId}}/versions
Content-Type: application/json

{
  "organizationId": "{{orgId}}",
  "unitId": "{{unitId}}",
  "contextId": "{{contextId}}",
  "schemaId": "{{schemaId}}",
  "schemaVersionId": "",
  "description": "Initial revision.",
  "specification": "event SchemaDefined { type eventType }",
  "status": "Published",
  "previousVersion": "1.0.1",
  "currentVersion": "1.0.2"
}
> {% client.global.set('schemaVersionId', response.body.schemaVersionId) %}

### Publish Schema Version
PATCH http://localhost:9019/organizations/{{orgId}}/units/{{unitId}}/contexts/{{contextId}}/schemas/{{schemaId}}/versions/{{schemaVersionId}}/status

'Published'


###
# Schema Queries

### Units of Organisation
GET http://localhost:9019/organizations/{{orgId}}/units
Accept: application/json

### Contexts of Unit
GET http://localhost:9019/organizations/{{orgId}}/units/{{unitId}}/contexts
Accept: application/json

###